version: '3.9'
services: 
  db:
      image: "mcr.microsoft.com/mssql/server"
      volumes:
        - ./db_data:/var/opt/mssql/data
      ports:
         - 1434:1433 
      environment: 
        SA_PASSWORD: 'JesusisLord!0'
        ACCEPT_EULA: 'Y'